elecciones/urls.py
from django.urls import path

from . import views

app_name = 'elecciones'

urlpatterns = [
    # ex: /elecciones/
    path('', views.index, name='index'),
    # ex: /elecciones/#/
    path('<int:region_id>/', views.detalle, name='detalle'),
    # ex: /elecciones/#/resultados/
    path('<int:region_id>/resultados/', views.resultados, name='resultados'),
    # ex: /elecciones/#/voto/
    path('<int:region_id>/voto/', views.votar, name='votar'),
]

lab04/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('elecciones/', include('elecciones.urls')),
    path('admin/', admin.site.urls),
]

elecciones/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    region_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Candidato(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    candidato_name = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

elecciones/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Candidato, Region

def index(request):
    latest_question_list = Region.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)

def detalle(request,region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'detalle.html', {'region' : region})

def votar(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    try:
        selected_candidato = region.candidato_set.get(pk=request.POST['candidato'])
    except (KeyError, Candidato.DoesNotExist):
        return render(request, 'detalle.html', {
            'region': region,
            'error_message': "No has seleccionado un candidato.",
        })
    else:
        selected_candidato.votos += 1
        selected_candidato.save()
        return HttpResponseRedirect(reverse('elecciones:resultados', args=(region_id,)))

def resultados(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    return render(request, 'resultados.html', {'region' : region})

elecciones/templates/detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><u></u><h1>{{region.region_name}}</h1></u></center>
    
    <ul>
    {% for candidato in region.candidato_set.all %}
        <li>{{ candidato.candidato_name }} -- {{ candidato.votos }} voto{{ candidato.votos|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'elecciones:resultados' region.id %}">Votar de nuevo</a><br><br>
    <a href="{% url 'elecciones:index' %}">Ver preguntas</a>        
</body>
</html>

elecciones/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><u><h1>Elecciones</h1></u></center>

    {% if latest_question_list %}
        <ul>
            {% for region in latest_question_list %}
                <li>
                    <a href="/elecciones/{{ region.id }}/">{{ region.region_name }}</a>
                </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay registros.</p>
    {% endif %}        
</body>
</html>

elecciones/templates/resultados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><u><h1>{{region.region_name}}</h1></u></center>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'elecciones:votar' region.id %}" method="post">
    {% csrf_token %}
    {% for candidato in region.candidato_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ candidato.id }}">
        <label for="candidato{{ forloop.counter }}">{{ candidato.candidato_name }}</label><br>
    {% endfor %}
    <br>
    <input  type="submit" value="Votar">
    </form>
    <br/>
    <a href="{% url 'elecciones:index' %}">Ver preguntas</a>
</body>
</html>